FROM confluentinc/cp-kafka-connect:7.6.1

RUN confluent-hub install --no-prompt wepay/kafka-connect-bigquery:latest
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4
RUN confluent-hub install --no-prompt snowflakeinc/snowflake-kafka-connector:latest
