-- Create a dedicated warehouse for this project (small, cost-efficient)
CREATE WAREHOUSE IF NOT EXISTS CDC_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create a database and schema for the CDC pipeline
CREATE DATABASE IF NOT EXISTS CDC_RAW;
CREATE SCHEMA IF NOT EXISTS CDC_RAW.INVOICES;

-- Create a dedicated role for the Kafka connector (least-privilege, not your main login)
CREATE ROLE IF NOT EXISTS KAFKA_CONNECTOR_ROLE;

GRANT USAGE ON WAREHOUSE CDC_WH TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON DATABASE CDC_RAW TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON SCHEMA CDC_RAW.INVOICES TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE TABLE ON SCHEMA CDC_RAW.INVOICES TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA CDC_RAW.INVOICES TO ROLE KAFKA_CONNECTOR_ROLE;

-- Create a dedicated user for the Kafka connector (key-pair auth will be added next step)
CREATE USER IF NOT EXISTS KAFKA_CONNECTOR_USER
  DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE
  DEFAULT_WAREHOUSE = CDC_WH;

GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECTOR_USER;
ALTER USER KAFKA_CONNECTOR_USER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2y7DS2RlL1gGgKzNcary54cThmQM+3pUwtY9HVULj3gRKMQBj9v+K48b5nX0eUHnNmS52Km43nGU646erhIkJqtPkK2jStr3bHRqmQGb+909mhLxMNnXrCaoIAHeCcX+tOZNgDRC+wIp/EcD6nQK5/WNGanBcJnet333+jU1fexepqLQmScwvpsaI4yNz2biVV6UY0wdSHUbEwoMLPU0FSgUw3ObzXpF9SJsGh5ayqTK2chuCK37Req2qcoe3L26ix6hKXAi3sMvmBPsiO/EpCJbEQ6akBCPoNpwScJxfCqXCU3Y+TuHVnKvDx6ZWCbFmswvqU+nK5ja2hqBDVj60wIDAQAB';