-- Create a dedicated warehouse for this project (small, cost-efficient)
CREATE WAREHOUSE IF NOT EXISTS CDC_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Create a database and schema for the CDC pipeline
CREATE DATABASE IF NOT EXISTS CDC_RAW;
CREATE SCHEMA IF NOT EXISTS CDC_RAW.INVOICES;

-- Create a dedicated role for the Kafka connector (least-privilege, not your main login)
CREATE ROLE IF NOT EXISTS KAFKA_CONNECTOR_ROLE;

GRANT USAGE ON WAREHOUSE CDC_WH TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON DATABASE CDC_RAW TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON SCHEMA CDC_RAW.INVOICES TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE TABLE ON SCHEMA CDC_RAW.INVOICES TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA CDC_RAW.INVOICES TO ROLE KAFKA_CONNECTOR_ROLE;

-- Create a dedicated user for the Kafka connector (key-pair auth will be added next step)
CREATE USER IF NOT EXISTS KAFKA_CONNECTOR_USER
  DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE
  DEFAULT_WAREHOUSE = CDC_WH;

GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECTOR_USER;
ALTER USER KAFKA_CONNECTOR_USER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr2julDyvZ71zfxkpJSspBYv+Y7FU5CK6+06FiQoBC44MMdKX0kKlzhQ1HzTzNjud+AdeeybCwzqSpwHKl8qk4q+oCw9dBgC1rRicRKtXyVQQQHQPvQVw51s2dWTh4Oa45WxpGO5S0e34smT5H2ZyolQfY5hxLXSc7Ck3Mhhdr4Uitxeu37sJ6ocduLtGXGDenI/z+WURD8CafIVkNur2ehjWjv0BHfDrHLVtDpISPfiLE1akUReumvQ2/6G6yBuY3ZVJytgf48xF/aR/vz2vSISNvxxdiRK1TNyXPcKT0+FWN1UEMoES8PcAa8I5zrgaHep6hw9STdfEKsfbfV7+DwIDAQAB';